---
title: 'Fake diamond: lmer on reaction times'
author: "Ryan Law"
date:   '`r format(Sys.time(), "%B %d, %Y")`'
output: html_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analysing reaction times

```{r cars}
library(tidyverse)

number_of_subjects = 13
subjects = sprintf("%02d", seq(1, number_of_subjects))
number_of_runs = 5

logs_dir = 'U:/ownCloud/projects/fake_diamond/scripts/analysis/behavioural/data'


# initialise dataframe
df_rt = data.frame()

for (subject in subjects) {
  
  for (run in 1:number_of_runs) {
    
    log_fname = file.path(logs_dir, sprintf("sub-%s_logfile.csv", subject))
    
    log_df = read.csv(log_fname)
    
  }
  
  df_rt <- bind_rows(df_rt, log_df)
}

df_rt = as_tibble(df_rt)


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
