---
title: 'Fake diamond: lmer on reaction times'
author: "Ryan Law"
date:   '`r format(Sys.time(), "%B %d, %Y")`'
output: html_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analysing reaction times

```{r read in logfiles}
library(tidyverse)
library(readr)

# read in all subject logfiles
list_of_logfiles <- list.files(path = 'U:/ownCloud/projects/fake_diamond/scripts/analysis/behavioural/data',
                               recursive = TRUE,
                               pattern = "\\.csv$",
                               full.names = TRUE)
group_data <- readr::read_csv(list_of_logfiles, id = "file_name")

group_data = select(group_data, participant, block_nr, trial_nr, item_nr, word1, word2, probe, response, RT, hit, composition, denotation, concreteness, specificity) # selecting relevant columns from logfiles
# group_data = mutate(group_data,
#                    RT = RT*1000, # converting RT units from sec to msec
#                    RT = log10(RT)) # log10 transform RT
group_data <- subset(group_data, is.na(group_data$specificity))
group_data <- subset(group_data, !is.na(group_data$probe))
# group_data = group_data[group_data$hit == 1, ] # only analysing reaction times from trials answered correctly

group_data = as_tibble(group_data)
group_data

table(group_data$participant) # counts in each level of structure
group_data %>% group_by(participant) %>% summarize(M = mean(RT), SD = sd(RT)) # some descriptive stats
group_data %>% ggplot(aes(x = RT, fill = composition)) +
 geom_density(alpha = 0.5) + theme_minimal() +
 scale_fill_brewer(palette = 'PuOr')
```

```{r look at individual subject's performance}

```